version: '3.7'
services:
  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_USER_LOGIN: user
      ACTIVEMQ_USER_PASSWORD: user
      ACTIVEMQ_ENABLED_SCHEDULER: 'true'
  timingstation-1:
    image: timingstation:latest
    container_name: timingstation-1
    ports:
      - "8081:8080"
    environment:
      STATION_ID: 1
      SECTION_ID: 1
    depends_on:
      - controllingstation-1
      - activemq
  timingstation-2:
    image: timingstation:latest
    container_name: timingstation-2
    ports:
      - "8082:8080"
    environment:
      STATION_ID: 2
      SECTION_ID: 1
    depends_on:
      - controllingstation-1
      - activemq
  timingstation-3:
    image: timingstation:latest
    container_name: timingstation-3
    ports:
      - "8083:8080"
    environment:
      STATION_ID: 3
      SECTION_ID: 1
    depends_on:
      - controllingstation-1
      - activemq
  timingstation-4:
    image: timingstation:latest
    container_name: timingstation-4
    ports:
      - "8084:8080"
    environment:
      STATION_ID: 4
      SECTION_ID: 1
    depends_on:
      - controllingstation-1
      - activemq
  controllingstation-1:
    image: controllingstation:latest
    container_name: controllingstation-1
    ports:
      - "8080:8080"
    environment:
      STATION_ID: 1
      SECTION_ID: 1
    depends_on:
      - activemq